-- DEMANDES : base Supabase
-- À exécuter UNE FOIS dans Supabase > SQL Editor.
-- Cette version utilise une authentification applicative simple avec des mots de passe
-- hachés côté navigateur. Pour une application sensible, utiliser Supabase Auth + RLS plus strictes.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username text unique not null,
  password_hash text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.members (
  id bigint generated by default as identity primary key,
  username text unique not null,
  password_hash text not null,
  role text not null,
  permissions jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.requests (
  id bigint generated by default as identity primary key,
  snap text not null,
  type text not null,
  question text not null,
  date date not null,
  lieu text,
  status text not null default 'En attente',
  reply text,
  reply_by text,
  created_at timestamptz not null default now()
);

alter table public.users enable row level security;
alter table public.members enable row level security;
alter table public.requests enable row level security;

drop policy if exists "public users all" on public.users;
drop policy if exists "public members all" on public.members;
drop policy if exists "public requests all" on public.requests;

create policy "public users all" on public.users for all to anon, authenticated using (true) with check (true);
create policy "public members all" on public.members for all to anon, authenticated using (true) with check (true);
create policy "public requests all" on public.requests for all to anon, authenticated using (true) with check (true);

-- Comptes équipe initiaux.
-- Les mots de passe sont des SHA-256.
insert into public.members (username,password_hash,role,permissions)
values
('Mathis','b4c8d414dade89a258c5965658bb38a9716f79cd04bfaa1927f0b32a137fa5d2','Administrateur','["all"]'::jsonb),
('Andry','99121007568154856daa129aa8b7284f3b2afe760557a3f921b05be293d2321a','Andry','["all"]'::jsonb),
('Joshua','960a1958c9995d7883603c2a222f4a2e668978f8077b2e70ea6e345001222d6f','Juge','["validate"]'::jsonb),
('Secretaire','8262609c11ebba75e05137c9a4fba9f82960014ebb5111fb9d4eb0371e4b9a1b','Secrétaire / Porte-parole','["reply","delete"]'::jsonb)
on conflict (username) do nothing;
